project/blog/urls.py
from django.urls import path
from .views import home, one_post, create_post


app_name = "blog"

urlpatterns = [
    path("home/", home, name="home"),
    path("one_post/<int:post_id>/", one_post, name="one_post"),
    path("create_post/", create_post, name="create_post"),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace="blog")),
]

project/blog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


class Post(models.Model):
    title = models.CharField(max_length=25, unique=True)
    content = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __repr__(self):
        return f"{self.title}"

    def get_absolute_url(self):
        return reverse("blog:one_post", args=[self.id])


class Comment(models.Model):
    content = models.TextField()
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="comments")

    def __repr__(self):
        return f"{self.content}"

project/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect, HttpResponse
from django.contrib.auth.models import User
from .models import Post, Comment


def home(request):
    posts = Post.objects.all()
    data = {"posts": posts}
    return render(request, "index.html", context=data)


def one_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    data = {"post": post}
    return render(request, "post.html", context=data)


def create_post(request):
    if request.method == "POST":
        title = request.POST.get("title")
        content = request.POST.get("content")
        author = get_object_or_404(User)
        try:
            post = Post(title=title, content=content, author=author)
            post.full_clean()
        except:
            return HttpResponse("<h1>Bad values</h1>")
        else:
            post.save()
        return redirect("blog:home")
    return render(request, "create_post.html")

project/blog/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Home{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>

    <div class="container mt-4">
      {% block content %}   
      {% endblock %}
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

project/blog/templates/create_post.html
{% extends 'base.html' %}

{% block title %}Create post{% endblock %}

{% block content %}
    <div class="conteiner w-50">
        <h1>Create post</h1>
        <form action="{% url 'blog:create_post' %}" method="post">
            {% csrf_token %}
            <label for="form-label">Title</label>
            <input type="text", name="title">

            <label for="form-label">Content</label>
            <textarea name="content" rows="10" class="form-control"></textarea>
            <button type="submit">Create</button>
        </form>
    </div>
{% endblock %}

project/blog/templates/index.html
{% extends 'base.html' %}


{% block content %}
<div>
    <h1>Hello, world! This is my first django run.</h1>
</div>

<div>
    <h2>All posts</h2>
    {% for post in posts %}
    <div>
        <h3>{{ post.title }}</h3>
        <p><a href="{{ post.get_absolute_url }}">Continue reading</a></p>
    </div>
    {% endfor %}
</div>
{% endblock %}

project/blog/templates/post.html
{% extends 'base.html' %}

{% block title %} {{post.title}} {% endblock %}

{% block content %}
    <div>
        <p>{{post.title}}</p>
        <p>{{post.content}}</p>
        <p><a href="{% url 'blog:home' %}">Go on home page</a></p>
    </div>
{% endblock %}